on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Build using CaC Action ğŸ—ï¸
        uses: kl13nt/courseware-as-code-action@v0.0.10
        with:
          debug: true # prints npm and next logs in case of successful build
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        permissions:
          contents: write
        with:
          folder: courseware-as-code-template-master/out # The folder the action should deploy.
